name       : terraform
version    : 1.3.7
release    : 17
source     :
    - https://github.com/hashicorp/terraform/archive/v1.3.7.tar.gz : 36bc7319bf97965144a38c2670f458752f7cb8e7fd783c216b4a24bebee2a8c4
license    : MPL-2.0
component  : programming.tools
summary    : Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.
description: |
    Terraform is a tool for building, changing, and versioning infrastructure safely and efficiently.
    Terraform can manage existing and popular service providers as well as custom in-house solutions.
networking : true
builddeps  :
    - golang
build      : |
    go mod vendor
    go build -o terraform-binary
install    : |
    install -Dm 00755 terraform-binary $installdir/usr/bin/terraform
