name       : terraform
version    : 1.1.2
release    : 15
source     :
    - https://github.com/hashicorp/terraform/archive/v1.1.2.tar.gz : fdb86ce8eeb5ccba851d9e806449653b2c2f0a14b4d1e3f4c82fd72ab032ded9
license    : MPL-2.0
component  : programming.tools
summary    : Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.
description: |
    Terraform is a tool for building, changing, and versioning infrastructure safely and efficiently.
    Terraform can manage existing and popular service providers as well as custom in-house solutions.
networking : true
builddeps  :
    - golang
build      : |
    go mod vendor
    go build -o terraform-binary
install    : |
    install -Dm 00755 terraform-binary $installdir/usr/bin/terraform
