name       : terraform
version    : 0.12.28
release    : 9
source     :
    - git|https://github.com/hashicorp/terraform : v0.12.28
license    : MPL-2.0
component  : programming.tools
summary    : Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.
description: |
    Terraform is a tool for building, changing, and versioning infrastructure safely and efficiently.
    Terraform can manage existing and popular service providers as well as custom in-house solutions.
builddeps  :
    - golang
build      : |
    go build -mod vendor -o terraform-binary
install    : |
    install -Dm 00755 terraform-binary $installdir/usr/bin/terraform
