name       : terraform
version    : 0.15.4
release    : 13
source     :
    - https://github.com/hashicorp/terraform/archive/v0.15.4.tar.gz : c94add2b677d6cbc2ca88d9eb154bdca0df26cdd397d44953a3ac9cdf7305480
license    : MPL-2.0
component  : programming.tools
summary    : Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.
description: |
    Terraform is a tool for building, changing, and versioning infrastructure safely and efficiently.
    Terraform can manage existing and popular service providers as well as custom in-house solutions.
networking : true
builddeps  :
    - golang
build      : |
    go mod vendor
    go build -o terraform-binary
install    : |
    install -Dm 00755 terraform-binary $installdir/usr/bin/terraform
