name       : terraform
version    : 0.11.7
release    : 1
source     :
    - https://github.com/hashicorp/terraform/archive/v0.11.7.tar.gz : f9a2730dcd68dad754cf0efa017d51929a7f333a89d07ddff3c6ff7b2d1e8be3
license    : MPL-2.0
component  : programming.tools
summary    : Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.
description: |
    Terraform is a tool for building, changing, and versioning infrastructure safely and efficiently. 
    Terraform can manage existing and popular service providers as well as custom in-house solutions.
builddeps  :
    - golang
build      : |
    mkdir -p src/github.com/hashicorp
    export GOPATH=`pwd`
    ln -sv `pwd` src/github.com/hashicorp/terraform
    cd src/github.com/hashicorp/terraform
    go build -o terraform-binary
install    : |
    cd src/github.com/hashicorp/terraform
    install -Dm 00755 terraform-binary $installdir/usr/bin/terraform
