name       : terraform
version    : 0.12.6
release    : 8
source     :
    - https://github.com/hashicorp/terraform/archive/v0.12.6.tar.gz : df108a45f5ba2658eed844c3a6647117324c99770e06cbd549b26dd7c20ee623
license    : MPL-2.0
component  : programming.tools
summary    : Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.
description: |
    Terraform is a tool for building, changing, and versioning infrastructure safely and efficiently.
    Terraform can manage existing and popular service providers as well as custom in-house solutions.
builddeps  :
    - golang
build      : |
    mkdir -p src/github.com/hashicorp
    export GOPATH=`pwd`
    ln -sv `pwd` src/github.com/hashicorp/terraform
    cd src/github.com/hashicorp/terraform
    go build -o terraform-binary
install    : |
    cd src/github.com/hashicorp/terraform
    install -Dm 00755 terraform-binary $installdir/usr/bin/terraform
