name       : terraform
version    : 0.13.5
release    : 11
source     :
    - https://github.com/hashicorp/terraform/archive/v0.13.5.tar.gz : c4bdb9e636550795862f13e0ae667a1d381bf2f6cd30c4dde54411afdd07aeab
license    : MPL-2.0
component  : programming.tools
summary    : Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.
description: |
    Terraform is a tool for building, changing, and versioning infrastructure safely and efficiently.
    Terraform can manage existing and popular service providers as well as custom in-house solutions.
builddeps  :
    - golang
build      : |
    go build -mod vendor -o terraform-binary
install    : |
    install -Dm 00755 terraform-binary $installdir/usr/bin/terraform
