name       : terraform
version    : 1.2.1
release    : 16
source     :
    - https://github.com/hashicorp/terraform/archive/v1.2.1.tar.gz : d244277c3b8d10afa8d130cfd9db3570995a03a34052952de1ab2368fc25ab1c
license    : MPL-2.0
component  : programming.tools
summary    : Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.
description: |
    Terraform is a tool for building, changing, and versioning infrastructure safely and efficiently.
    Terraform can manage existing and popular service providers as well as custom in-house solutions.
networking : true
builddeps  :
    - golang
build      : |
    go mod vendor
    go build -o terraform-binary
install    : |
    install -Dm 00755 terraform-binary $installdir/usr/bin/terraform
