name       : terraform
version    : 1.5.2
release    : 18
source     :
    - https://github.com/hashicorp/terraform/archive/v1.5.2.tar.gz : 1fb4e2e583a65583a24a8af3699fd0a9cd762da71b2436d0b62e448fe89180e9
license    : MPL-2.0
component  : programming.tools
summary    : Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.
description: |
    Terraform is a tool for building, changing, and versioning infrastructure safely and efficiently.
    Terraform can manage existing and popular service providers as well as custom in-house solutions.
networking : true
builddeps  :
    - golang
build      : |
    go mod vendor
    go build -o terraform-binary
install    : |
    install -Dm 00755 terraform-binary $installdir/usr/bin/terraform
