name       : terraform
version    : 1.5.5
release    : 19
source     :
    - https://github.com/hashicorp/terraform/archive/v1.5.5.tar.gz : 06a72b5ecda4e10d5f2a3c7627420cf0ca0a6b7b47ef0ae151cc1c6ef38eb2fe
license    : MPL-2.0
component  : programming.tools
summary    : Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.
description: |
    Terraform is a tool for building, changing, and versioning infrastructure safely and efficiently.
    Terraform can manage existing and popular service providers as well as custom in-house solutions.
networking : true
builddeps  :
    - golang
build      : |
    go mod vendor
    go build -o terraform-binary
install    : |
    install -Dm 00755 terraform-binary $installdir/usr/bin/terraform
