name       : terraform
version    : 0.11.10
release    : 3
source     :
    - https://github.com/hashicorp/terraform/archive/v0.11.10.tar.gz : 3cdf16618f7291ac70793f680d859223907039bdf559ca5b5e49fae7df2e736d
license    : MPL-2.0
component  : programming.tools
summary    : Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.
description: "Terraform is a tool for building, changing, and versioning infrastructure safely and efficiently. \nTerraform can manage existing and popular service providers as well as custom in-house solutions.\n"
builddeps  :
    - golang
build      : |
    mkdir -p src/github.com/hashicorp
    export GOPATH=`pwd`
    ln -sv `pwd` src/github.com/hashicorp/terraform
    cd src/github.com/hashicorp/terraform
    go build -o terraform-binary
install    : |
    cd src/github.com/hashicorp/terraform
    install -Dm 00755 terraform-binary $installdir/usr/bin/terraform
